using System;
using Contract;
using Grpc.Core;
using Grpc.Net.Client;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using ServiceModel.Grpc.Client.DependencyInjection;

namespace Client.DesignTime;

public static class DemoGrpcNetChannel
{
    public static void ConfigureServices1(IServiceCollection services)
    {
        // provide Channel
        services.AddSingleton(CreateChannel);

        // optional ClientFactory configuration
        services
            .AddServiceModelGrpcClientFactory((factoryOptions, provider) =>
            {
                // ...
            })
            // use ICalculator proxy generated by ServiceModel.Grpc.DesignTime
            .AddCalculatorClient((clientOptions, provider) =>
            {
                // optional ICalculator proxy configuration
            });

        // use IRandomNumberGenerator proxy generated by ServiceModel.Grpc.DesignTime
        services.AddRandomNumberGeneratorClient();
    }

    public static void ConfigureServices2(IServiceCollection services)
    {
        services
            .AddServiceModelGrpcClientFactory()
            .ConfigureDefaultChannel(ChannelProviderFactory.Transient(CreateChannel)) // provide Channel
            // use ICalculator proxy generated by ServiceModel.Grpc.DesignTime
            .AddCalculatorClient();

        // use IRandomNumberGenerator proxy generated by ServiceModel.Grpc.DesignTime
        services.AddRandomNumberGeneratorClient((clientOptions, provider) =>
        {
            // optional IRandomNumberGenerator proxy configuration
        });
    }

    public static void ConfigureServices3(IServiceCollection services)
    {
        // use ICalculator proxy generated by ServiceModel.Grpc.DesignTime
        services.AddCalculatorClient(
            channel: ChannelProviderFactory.Transient(CreateChannel));

        // use IRandomNumberGenerator proxy generated by ServiceModel.Grpc.DesignTime
        services.AddRandomNumberGeneratorClient(
            channel: ChannelProviderFactory.Transient(CreateChannel));
    }

    private static ChannelBase CreateChannel(IServiceProvider serviceProvider)
    {
        var serverAddress = serviceProvider.GetRequiredService<IOptions<ClientConfiguration>>().Value.ServerAddress;
        return GrpcChannel.ForAddress(serverAddress, new GrpcChannelOptions());
    }
}