//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.Serialization;

namespace ServiceModel.Grpc.Channel
{
    [Serializable]
    [DataContract(Name = "m", Namespace = "s")]
    internal sealed class Message
    {
        public Message()
        {
        }

    }

    [Serializable]
    [DataContract(Name = "m", Namespace = "s")]
    internal sealed class Message<T1>
    {
        private T1 _value1;

        public Message()
        {
        }

        public Message(T1 value1)
        {
            _value1 = value1;
        }

        [DataMember(Name = "v1", Order = 1)]
        public T1 Value1 { get => _value1; set => _value1 = value; }

    }

    [Serializable]
    [DataContract(Name = "m", Namespace = "s")]
    internal sealed class Message<T1, T2>
    {
        private T1 _value1;

        private T2 _value2;

        public Message()
        {
        }

        public Message(T1 value1, T2 value2)
        {
            _value1 = value1;
            _value2 = value2;
        }

        [DataMember(Name = "v1", Order = 1)]
        public T1 Value1 { get => _value1; set => _value1 = value; }

        [DataMember(Name = "v2", Order = 2)]
        public T2 Value2 { get => _value2; set => _value2 = value; }

    }

    [Serializable]
    [DataContract(Name = "m", Namespace = "s")]
    internal sealed class Message<T1, T2, T3>
    {
        private T1 _value1;

        private T2 _value2;

        private T3 _value3;

        public Message()
        {
        }

        public Message(T1 value1, T2 value2, T3 value3)
        {
            _value1 = value1;
            _value2 = value2;
            _value3 = value3;
        }

        [DataMember(Name = "v1", Order = 1)]
        public T1 Value1 { get => _value1; set => _value1 = value; }

        [DataMember(Name = "v2", Order = 2)]
        public T2 Value2 { get => _value2; set => _value2 = value; }

        [DataMember(Name = "v3", Order = 3)]
        public T3 Value3 { get => _value3; set => _value3 = value; }

    }

}