//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;

#nullable enable

namespace ServiceModel.Grpc.Channel;

/// <summary>
/// This API supports ServiceModel.Grpc infrastructure and is not intended to be used directly from your code.
/// This API may change or be removed in future releases.
/// </summary>
[Serializable]
[DataContract(Name = "m", Namespace = "s")]
[Browsable(false)]
[EditorBrowsable(EditorBrowsableState.Never)]
public sealed partial class Message
{
    /// <exclude />
    public Message()
    {
    }

}

/// <summary>
/// This API supports ServiceModel.Grpc infrastructure and is not intended to be used directly from your code.
/// This API may change or be removed in future releases.
/// </summary>
[Serializable]
[DataContract(Name = "m", Namespace = "s")]
[Browsable(false)]
[EditorBrowsable(EditorBrowsableState.Never)]
public sealed partial class Message<T1>
{
    /// <exclude />
    public Message()
    {
    }

    /// <exclude />
    public Message(T1? value1)
    {
        Value1 = value1;
    }

    /// <exclude />
    [DataMember(Name = "v1", Order = 1)]
    public T1? Value1 { get; set; }

}

/// <summary>
/// This API supports ServiceModel.Grpc infrastructure and is not intended to be used directly from your code.
/// This API may change or be removed in future releases.
/// </summary>
[Serializable]
[DataContract(Name = "m", Namespace = "s")]
[Browsable(false)]
[EditorBrowsable(EditorBrowsableState.Never)]
public sealed partial class Message<T1, T2>
{
    /// <exclude />
    public Message()
    {
    }

    /// <exclude />
    public Message(T1? value1, T2? value2)
    {
        Value1 = value1;
        Value2 = value2;
    }

    /// <exclude />
    [DataMember(Name = "v1", Order = 1)]
    public T1? Value1 { get; set; }

    /// <exclude />
    [DataMember(Name = "v2", Order = 2)]
    public T2? Value2 { get; set; }

}

/// <summary>
/// This API supports ServiceModel.Grpc infrastructure and is not intended to be used directly from your code.
/// This API may change or be removed in future releases.
/// </summary>
[Serializable]
[DataContract(Name = "m", Namespace = "s")]
[Browsable(false)]
[EditorBrowsable(EditorBrowsableState.Never)]
public sealed partial class Message<T1, T2, T3>
{
    /// <exclude />
    public Message()
    {
    }

    /// <exclude />
    public Message(T1? value1, T2? value2, T3? value3)
    {
        Value1 = value1;
        Value2 = value2;
        Value3 = value3;
    }

    /// <exclude />
    [DataMember(Name = "v1", Order = 1)]
    public T1? Value1 { get; set; }

    /// <exclude />
    [DataMember(Name = "v2", Order = 2)]
    public T2? Value2 { get; set; }

    /// <exclude />
    [DataMember(Name = "v3", Order = 3)]
    public T3? Value3 { get; set; }

}

